
2023-05-23 09:56:06,246 - INFO - buying power is: 308353.4
2023-05-23 09:56:06,248 - INFO - last trade price is: 27382.8
2023-05-23 09:56:06,249 - INFO - holding amount is: 0.555827866
2023-05-23 09:56:09,095 - INFO - Bought 1.1308324509693726 of BTC/USD at price: 27267.823782
2023-05-23 09:56:09,297 - INFO - last trade price is: 27267.823782
2023-05-23 10:02:06,815 - INFO - buying power is: 308353.4
2023-05-23 10:02:06,818 - INFO - last trade price is: 27267.823782
2023-05-23 10:02:06,818 - INFO - holding amount is: 1.685303316
2023-05-23 10:40:21,219 - INFO - buying power is: 308353.4
2023-05-23 10:40:21,219 - INFO - last trade price is: 27267.823782
2023-05-23 10:40:21,219 - INFO - holding amount is: 1.685303316
2023-05-23 10:45:11,068 - INFO - buying power is: 308353.4
2023-05-23 10:45:11,069 - INFO - last trade price is: 27267.823782
2023-05-23 10:45:11,069 - INFO - holding amount is: 1.685303316
2023-05-23 10:45:48,425 - INFO - Bought 1.1320205314651322 of BTC/USD at price: 27239.2056
2023-05-23 10:45:48,627 - INFO - last trade price is: 27239.2056
2023-05-23 10:51:15,155 - INFO - buying power is: 308353.4
2023-05-23 10:51:15,157 - INFO - last trade price is: 27239.2056
2023-05-23 10:51:15,158 - INFO - holding amount is: 2.81596542
2023-05-23 12:17:03,549 - INFO - buying power is: 308353.4
2023-05-23 12:17:03,550 - INFO - last trade price is: 27239.2056
2023-05-23 12:17:03,550 - INFO - holding amount is: 2.81596542
2023-05-23 13:18:18,610 - ERROR - Buy Order submission failed
Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1322, in getresponse
    response.begin()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 357, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='paper-api.alpaca.markets', port=443): Read timed out. (read timeout=None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/main.py", line 73, in grid_trading
    self.api.submit_order(ticker, buying_amount, 'buy', 'limit', time_in_force='gtc',limit_price=ask_price)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 429, in submit_order
    resp = self.post('/orders', params)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 253, in post
    return self._request('POST', path, data)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 232, in _one_request
    resp = self._session.request(method, url, **opts)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='paper-api.alpaca.markets', port=443): Read timed out. (read timeout=None)
2023-05-23 13:18:18,613 - INFO - last trade price is: 27239.2056
2023-05-23 13:18:49,375 - ERROR - Buy Order submission failed
Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 234, in _one_request
    resp.raise_for_status()
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://paper-api.alpaca.markets/v2/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/main.py", line 73, in grid_trading
    self.api.submit_order(ticker, buying_amount, 'buy', 'limit', time_in_force='gtc',limit_price=ask_price)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 429, in submit_order
    resp = self.post('/orders', params)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 253, in post
    return self._request('POST', path, data)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 242, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: insufficient balance for USD (requested: 30835.339998820492, available: 23491.66)
2023-05-23 13:18:49,380 - INFO - last trade price is: 27239.2056
2023-05-23 13:18:50,684 - ERROR - Buy Order submission failed
Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 234, in _one_request
    resp.raise_for_status()
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://paper-api.alpaca.markets/v2/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/main.py", line 73, in grid_trading
    self.api.submit_order(ticker, buying_amount, 'buy', 'limit', time_in_force='gtc',limit_price=ask_price)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 429, in submit_order
    resp = self.post('/orders', params)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 253, in post
    return self._request('POST', path, data)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 242, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: insufficient balance for USD (requested: 30835.3399796356551, available: 23491.66)
2023-05-23 13:18:50,685 - INFO - last trade price is: 27239.2056
2023-05-23 13:18:51,991 - ERROR - Buy Order submission failed
Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 234, in _one_request
    resp.raise_for_status()
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://paper-api.alpaca.markets/v2/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/main.py", line 73, in grid_trading
    self.api.submit_order(ticker, buying_amount, 'buy', 'limit', time_in_force='gtc',limit_price=ask_price)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 429, in submit_order
    resp = self.post('/orders', params)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 253, in post
    return self._request('POST', path, data)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 242, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: insufficient balance for USD (requested: 30835.3399796356551, available: 23491.66)
2023-05-23 13:18:51,992 - INFO - last trade price is: 27239.2056
2023-05-23 13:18:53,287 - ERROR - Buy Order submission failed
Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 234, in _one_request
    resp.raise_for_status()
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://paper-api.alpaca.markets/v2/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/main.py", line 73, in grid_trading
    self.api.submit_order(ticker, buying_amount, 'buy', 'limit', time_in_force='gtc',limit_price=ask_price)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 429, in submit_order
    resp = self.post('/orders', params)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 253, in post
    return self._request('POST', path, data)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 242, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: insufficient balance for USD (requested: 30835.3399796356551, available: 23491.66)
2023-05-23 13:18:53,288 - INFO - last trade price is: 27239.2056
2023-05-23 13:18:54,590 - ERROR - Buy Order submission failed
Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 234, in _one_request
    resp.raise_for_status()
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://paper-api.alpaca.markets/v2/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/main.py", line 73, in grid_trading
    self.api.submit_order(ticker, buying_amount, 'buy', 'limit', time_in_force='gtc',limit_price=ask_price)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 429, in submit_order
    resp = self.post('/orders', params)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 253, in post
    return self._request('POST', path, data)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 242, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: insufficient balance for USD (requested: 30835.3399858251153, available: 23491.66)
2023-05-23 13:18:54,591 - INFO - last trade price is: 27239.2056
2023-05-23 13:18:55,891 - ERROR - Buy Order submission failed
Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 234, in _one_request
    resp.raise_for_status()
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://paper-api.alpaca.markets/v2/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/main.py", line 73, in grid_trading
    self.api.submit_order(ticker, buying_amount, 'buy', 'limit', time_in_force='gtc',limit_price=ask_price)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 429, in submit_order
    resp = self.post('/orders', params)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 253, in post
    return self._request('POST', path, data)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 242, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: insufficient balance for USD (requested: 30835.3399858251153, available: 23491.66)
2023-05-23 13:18:55,893 - INFO - last trade price is: 27239.2056
2023-05-23 13:18:57,192 - ERROR - Buy Order submission failed
Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 234, in _one_request
    resp.raise_for_status()
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://paper-api.alpaca.markets/v2/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/main.py", line 73, in grid_trading
    self.api.submit_order(ticker, buying_amount, 'buy', 'limit', time_in_force='gtc',limit_price=ask_price)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 429, in submit_order
    resp = self.post('/orders', params)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 253, in post
    return self._request('POST', path, data)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 242, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: insufficient balance for USD (requested: 30835.3399858251153, available: 23491.66)
2023-05-23 13:18:57,194 - INFO - last trade price is: 27239.2056
2023-05-23 13:18:58,482 - ERROR - Buy Order submission failed
Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 234, in _one_request
    resp.raise_for_status()
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://paper-api.alpaca.markets/v2/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/main.py", line 73, in grid_trading
    self.api.submit_order(ticker, buying_amount, 'buy', 'limit', time_in_force='gtc',limit_price=ask_price)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 429, in submit_order
    resp = self.post('/orders', params)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 253, in post
    return self._request('POST', path, data)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 242, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: insufficient balance for USD (requested: 30835.3399858251153, available: 23491.66)
2023-05-23 13:18:58,483 - INFO - last trade price is: 27239.2056
2023-05-23 13:51:58,551 - ERROR - Buy Order submission failed
Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1322, in getresponse
    response.begin()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 357, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='paper-api.alpaca.markets', port=443): Read timed out. (read timeout=None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/main.py", line 73, in grid_trading
    self.api.submit_order(ticker, buying_amount, 'buy', 'limit', time_in_force='gtc',limit_price=ask_price)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 429, in submit_order
    resp = self.post('/orders', params)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 253, in post
    return self._request('POST', path, data)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 232, in _one_request
    resp = self._session.request(method, url, **opts)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='paper-api.alpaca.markets', port=443): Read timed out. (read timeout=None)
2023-05-23 13:51:58,557 - INFO - last trade price is: 27239.2056
2023-05-23 14:35:44,599 - INFO - buying power is: 308353.4
2023-05-23 14:35:44,602 - INFO - last trade price is: 27239.2056
2023-05-23 14:35:44,602 - INFO - holding amount is: 2.81596542
2023-05-23 14:41:45,154 - INFO - buying power is: 308353.4
2023-05-23 14:41:45,157 - INFO - last trade price is: 27239.2056
2023-05-23 14:41:45,157 - INFO - holding amount is: 2.81596542
2023-05-23 14:47:46,061 - INFO - buying power is: 308353.4
2023-05-23 14:47:46,063 - INFO - last trade price is: 27239.2056
2023-05-23 14:47:46,063 - INFO - holding amount is: 2.81596542
2023-05-23 14:53:46,587 - INFO - buying power is: 308353.4
2023-05-23 14:53:46,590 - INFO - last trade price is: 27239.2056
2023-05-23 14:53:46,590 - INFO - holding amount is: 2.81596542
2023-05-23 14:59:48,813 - INFO - buying power is: 308353.4
2023-05-23 14:59:48,815 - INFO - last trade price is: 27239.2056
2023-05-23 14:59:48,815 - INFO - holding amount is: 2.81596542
2023-05-23 15:35:35,569 - INFO - buying power is: 308353.4
2023-05-23 15:35:35,572 - INFO - last trade price is: 27239.2056
2023-05-23 15:35:35,572 - INFO - holding amount is: 2.81596542
2023-05-23 15:41:36,900 - INFO - buying power is: 308353.4
2023-05-23 15:41:36,902 - INFO - last trade price is: 27239.2056
2023-05-23 15:41:36,903 - INFO - holding amount is: 2.81596542
2023-05-23 16:25:43,111 - INFO - buying power is: 308353.4
2023-05-23 16:25:43,114 - INFO - last trade price is: 27239.2056
2023-05-23 16:25:43,114 - INFO - holding amount is: 2.81596542
2023-05-23 16:27:34,795 - INFO - Sold out of -1s
2023-05-23 16:27:34,796 - INFO - last trade price is: 27256.10390924
2023-05-23 16:31:44,345 - INFO - buying power is: 308353.4
2023-05-23 16:31:44,348 - INFO - last trade price is: 27256.10390924
2023-05-23 16:31:44,348 - INFO - holding amount is: 1.684646722
2023-05-23 17:28:05,529 - INFO - buying power is: 308353.4
2023-05-23 17:28:05,531 - INFO - last trade price is: 27256.10390924
2023-05-23 17:28:05,531 - INFO - holding amount is: 1.684646722
2023-05-23 17:29:20,055 - INFO - buying power is: 308353.4
2023-05-23 17:29:20,056 - INFO - last trade price is: 27256.10390924
2023-05-23 17:29:20,056 - INFO - holding amount is: 1.684646722
2023-05-23 17:32:14,790 - INFO - Bought 1.1325142473442351 of BTC/USD at price: 27227.33075748
2023-05-23 17:32:14,989 - INFO - last trade price is: 27227.33075748
2023-05-23 17:34:18,205 - INFO - buying power is: 308353.4
2023-05-23 17:34:18,206 - INFO - last trade price is: 27227.33075748
2023-05-23 17:34:18,206 - INFO - holding amount is: 2.81580195
2023-05-23 17:40:17,796 - INFO - buying power is: 308353.4
2023-05-23 17:40:17,797 - INFO - last trade price is: 27227.33075748
2023-05-23 17:40:17,797 - INFO - holding amount is: 2.81580195
2023-05-23 17:46:17,573 - INFO - buying power is: 308353.4
2023-05-23 17:46:17,576 - INFO - last trade price is: 27227.33075748
2023-05-23 17:46:17,576 - INFO - holding amount is: 2.81580195
2023-05-23 17:52:17,565 - INFO - buying power is: 308353.4
2023-05-23 17:52:17,567 - INFO - last trade price is: 27227.33075748
2023-05-23 17:52:17,567 - INFO - holding amount is: 2.81580195
2023-05-23 17:58:17,667 - INFO - buying power is: 308353.4
2023-05-23 17:58:17,669 - INFO - last trade price is: 27227.33075748
2023-05-23 17:58:17,669 - INFO - holding amount is: 2.81580195
2023-05-23 18:04:16,805 - INFO - buying power is: 308353.4
2023-05-23 18:04:16,805 - INFO - last trade price is: 27227.33075748
2023-05-23 18:04:16,805 - INFO - holding amount is: 2.81580195
2023-05-23 18:09:24,113 - ERROR - Buy Order submission failed
Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 234, in _one_request
    resp.raise_for_status()
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://paper-api.alpaca.markets/v2/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/main.py", line 73, in grid_trading
    self.api.submit_order(ticker, buying_amount, 'buy', 'limit', time_in_force='gtc',limit_price=ask_price)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 429, in submit_order
    resp = self.post('/orders', params)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 253, in post
    return self._request('POST', path, data)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 242, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: insufficient balance for USD (requested: 30835.33999492995847865, available: 23454.63)
2023-05-23 18:09:24,119 - INFO - last trade price is: 27227.33075748
2023-05-23 18:09:25,426 - ERROR - Buy Order submission failed
Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 234, in _one_request
    resp.raise_for_status()
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://paper-api.alpaca.markets/v2/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/main.py", line 73, in grid_trading
    self.api.submit_order(ticker, buying_amount, 'buy', 'limit', time_in_force='gtc',limit_price=ask_price)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 429, in submit_order
    resp = self.post('/orders', params)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 253, in post
    return self._request('POST', path, data)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 242, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: insufficient balance for USD (requested: 30835.33999492995847865, available: 23454.63)
2023-05-23 18:09:25,427 - INFO - last trade price is: 27227.33075748
2023-05-23 18:09:26,723 - ERROR - Buy Order submission failed
Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 234, in _one_request
    resp.raise_for_status()
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://paper-api.alpaca.markets/v2/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/main.py", line 73, in grid_trading
    self.api.submit_order(ticker, buying_amount, 'buy', 'limit', time_in_force='gtc',limit_price=ask_price)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 429, in submit_order
    resp = self.post('/orders', params)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 253, in post
    return self._request('POST', path, data)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 242, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: insufficient balance for USD (requested: 30835.339979092572, available: 23454.63)
2023-05-23 18:09:26,724 - INFO - last trade price is: 27227.33075748
2023-05-23 18:09:28,004 - ERROR - Buy Order submission failed
Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 234, in _one_request
    resp.raise_for_status()
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://paper-api.alpaca.markets/v2/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/main.py", line 73, in grid_trading
    self.api.submit_order(ticker, buying_amount, 'buy', 'limit', time_in_force='gtc',limit_price=ask_price)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 429, in submit_order
    resp = self.post('/orders', params)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 253, in post
    return self._request('POST', path, data)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 242, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: insufficient balance for USD (requested: 30835.339979092572, available: 23454.63)
2023-05-23 18:09:28,005 - INFO - last trade price is: 27227.33075748
2023-05-23 18:09:29,276 - ERROR - Buy Order submission failed
Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 234, in _one_request
    resp.raise_for_status()
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://paper-api.alpaca.markets/v2/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/main.py", line 73, in grid_trading
    self.api.submit_order(ticker, buying_amount, 'buy', 'limit', time_in_force='gtc',limit_price=ask_price)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 429, in submit_order
    resp = self.post('/orders', params)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 253, in post
    return self._request('POST', path, data)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 242, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: insufficient balance for USD (requested: 30835.339979092572, available: 23454.63)
2023-05-23 18:09:29,278 - INFO - last trade price is: 27227.33075748
2023-05-23 18:09:30,598 - ERROR - Buy Order submission failed
Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 234, in _one_request
    resp.raise_for_status()
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://paper-api.alpaca.markets/v2/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/main.py", line 73, in grid_trading
    self.api.submit_order(ticker, buying_amount, 'buy', 'limit', time_in_force='gtc',limit_price=ask_price)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 429, in submit_order
    resp = self.post('/orders', params)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 253, in post
    return self._request('POST', path, data)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 242, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: insufficient balance for USD (requested: 30835.339989253632, available: 23454.63)
2023-05-23 18:09:30,599 - INFO - last trade price is: 27227.33075748
2023-05-23 18:09:31,899 - ERROR - Buy Order submission failed
Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 234, in _one_request
    resp.raise_for_status()
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://paper-api.alpaca.markets/v2/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/main.py", line 73, in grid_trading
    self.api.submit_order(ticker, buying_amount, 'buy', 'limit', time_in_force='gtc',limit_price=ask_price)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 429, in submit_order
    resp = self.post('/orders', params)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 253, in post
    return self._request('POST', path, data)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 242, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: insufficient balance for USD (requested: 30835.339989253632, available: 23454.63)
2023-05-23 18:09:31,900 - INFO - last trade price is: 27227.33075748
2023-05-23 18:09:33,190 - ERROR - Buy Order submission failed
Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 234, in _one_request
    resp.raise_for_status()
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://paper-api.alpaca.markets/v2/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/main.py", line 73, in grid_trading
    self.api.submit_order(ticker, buying_amount, 'buy', 'limit', time_in_force='gtc',limit_price=ask_price)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 429, in submit_order
    resp = self.post('/orders', params)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 253, in post
    return self._request('POST', path, data)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 242, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: insufficient balance for USD (requested: 30835.339989253632, available: 23454.63)
2023-05-23 18:09:33,192 - INFO - last trade price is: 27227.33075748
2023-05-23 18:09:34,482 - ERROR - Buy Order submission failed
Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 234, in _one_request
    resp.raise_for_status()
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://paper-api.alpaca.markets/v2/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/main.py", line 73, in grid_trading
    self.api.submit_order(ticker, buying_amount, 'buy', 'limit', time_in_force='gtc',limit_price=ask_price)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 429, in submit_order
    resp = self.post('/orders', params)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 253, in post
    return self._request('POST', path, data)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 242, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: insufficient balance for USD (requested: 30835.339989253632, available: 23454.63)
2023-05-23 18:09:34,489 - INFO - last trade price is: 27227.33075748
2023-05-23 18:09:40,549 - ERROR - Buy Order submission failed
Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 234, in _one_request
    resp.raise_for_status()
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://paper-api.alpaca.markets/v2/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/main.py", line 73, in grid_trading
    self.api.submit_order(ticker, buying_amount, 'buy', 'limit', time_in_force='gtc',limit_price=ask_price)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 429, in submit_order
    resp = self.post('/orders', params)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 253, in post
    return self._request('POST', path, data)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 242, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: insufficient balance for USD (requested: 30835.33998912596463678, available: 23454.63)
2023-05-23 18:09:40,550 - INFO - last trade price is: 27227.33075748
2023-05-23 18:09:41,830 - ERROR - Buy Order submission failed
Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 234, in _one_request
    resp.raise_for_status()
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://paper-api.alpaca.markets/v2/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/main.py", line 73, in grid_trading
    self.api.submit_order(ticker, buying_amount, 'buy', 'limit', time_in_force='gtc',limit_price=ask_price)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 429, in submit_order
    resp = self.post('/orders', params)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 253, in post
    return self._request('POST', path, data)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 242, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: insufficient balance for USD (requested: 30835.33998912596463678, available: 23454.63)
2023-05-23 18:09:41,831 - INFO - last trade price is: 27227.33075748
2023-05-23 18:09:43,111 - ERROR - Buy Order submission failed
Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 234, in _one_request
    resp.raise_for_status()
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://paper-api.alpaca.markets/v2/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/main.py", line 73, in grid_trading
    self.api.submit_order(ticker, buying_amount, 'buy', 'limit', time_in_force='gtc',limit_price=ask_price)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 429, in submit_order
    resp = self.post('/orders', params)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 253, in post
    return self._request('POST', path, data)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 242, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: insufficient balance for USD (requested: 30835.33998912596463678, available: 23454.63)
2023-05-23 18:09:43,112 - INFO - last trade price is: 27227.33075748
2023-05-23 18:09:44,390 - ERROR - Buy Order submission failed
Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 234, in _one_request
    resp.raise_for_status()
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://paper-api.alpaca.markets/v2/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/main.py", line 73, in grid_trading
    self.api.submit_order(ticker, buying_amount, 'buy', 'limit', time_in_force='gtc',limit_price=ask_price)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 429, in submit_order
    resp = self.post('/orders', params)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 253, in post
    return self._request('POST', path, data)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 242, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: insufficient balance for USD (requested: 30835.33998912596463678, available: 23454.63)
2023-05-23 18:09:44,391 - INFO - last trade price is: 27227.33075748
2023-05-23 18:09:49,286 - ERROR - Buy Order submission failed
Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 234, in _one_request
    resp.raise_for_status()
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://paper-api.alpaca.markets/v2/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/main.py", line 73, in grid_trading
    self.api.submit_order(ticker, buying_amount, 'buy', 'limit', time_in_force='gtc',limit_price=ask_price)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 429, in submit_order
    resp = self.post('/orders', params)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 253, in post
    return self._request('POST', path, data)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 242, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: insufficient balance for USD (requested: 30835.3399795132844, available: 23454.63)
2023-05-23 18:09:49,287 - INFO - last trade price is: 27227.33075748
2023-05-23 18:09:50,578 - ERROR - Buy Order submission failed
Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 234, in _one_request
    resp.raise_for_status()
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://paper-api.alpaca.markets/v2/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/main.py", line 73, in grid_trading
    self.api.submit_order(ticker, buying_amount, 'buy', 'limit', time_in_force='gtc',limit_price=ask_price)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 429, in submit_order
    resp = self.post('/orders', params)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 253, in post
    return self._request('POST', path, data)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 242, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: insufficient balance for USD (requested: 30835.3399795132844, available: 23454.63)
2023-05-23 18:09:50,579 - INFO - last trade price is: 27227.33075748
2023-05-23 18:09:51,869 - ERROR - Buy Order submission failed
Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 234, in _one_request
    resp.raise_for_status()
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://paper-api.alpaca.markets/v2/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/main.py", line 73, in grid_trading
    self.api.submit_order(ticker, buying_amount, 'buy', 'limit', time_in_force='gtc',limit_price=ask_price)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 429, in submit_order
    resp = self.post('/orders', params)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 253, in post
    return self._request('POST', path, data)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 242, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: insufficient balance for USD (requested: 30835.3399795132844, available: 23454.63)
2023-05-23 18:09:51,870 - INFO - last trade price is: 27227.33075748
2023-05-23 18:09:53,150 - ERROR - Buy Order submission failed
Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 234, in _one_request
    resp.raise_for_status()
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://paper-api.alpaca.markets/v2/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/main.py", line 73, in grid_trading
    self.api.submit_order(ticker, buying_amount, 'buy', 'limit', time_in_force='gtc',limit_price=ask_price)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 429, in submit_order
    resp = self.post('/orders', params)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 253, in post
    return self._request('POST', path, data)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 242, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: insufficient balance for USD (requested: 30835.3399795132844, available: 23454.63)
2023-05-23 18:09:53,152 - INFO - last trade price is: 27227.33075748
2023-05-23 18:10:07,515 - ERROR - Buy Order submission failed
Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 234, in _one_request
    resp.raise_for_status()
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://paper-api.alpaca.markets/v2/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/main.py", line 73, in grid_trading
    self.api.submit_order(ticker, buying_amount, 'buy', 'limit', time_in_force='gtc',limit_price=ask_price)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 429, in submit_order
    resp = self.post('/orders', params)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 253, in post
    return self._request('POST', path, data)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 242, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: insufficient balance for USD (requested: 30835.3399877196, available: 23454.63)
2023-05-23 18:10:07,517 - INFO - last trade price is: 27227.33075748
2023-05-23 18:10:08,797 - ERROR - Buy Order submission failed
Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 234, in _one_request
    resp.raise_for_status()
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://paper-api.alpaca.markets/v2/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/main.py", line 73, in grid_trading
    self.api.submit_order(ticker, buying_amount, 'buy', 'limit', time_in_force='gtc',limit_price=ask_price)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 429, in submit_order
    resp = self.post('/orders', params)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 253, in post
    return self._request('POST', path, data)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 242, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: insufficient balance for USD (requested: 30835.3399877196, available: 23454.63)
2023-05-23 18:10:08,798 - INFO - last trade price is: 27227.33075748
2023-05-23 18:10:10,077 - ERROR - Buy Order submission failed
Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 234, in _one_request
    resp.raise_for_status()
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://paper-api.alpaca.markets/v2/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/main.py", line 73, in grid_trading
    self.api.submit_order(ticker, buying_amount, 'buy', 'limit', time_in_force='gtc',limit_price=ask_price)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 429, in submit_order
    resp = self.post('/orders', params)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 253, in post
    return self._request('POST', path, data)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 242, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: insufficient balance for USD (requested: 30835.3399877196, available: 23454.63)
2023-05-23 18:10:10,077 - INFO - last trade price is: 27227.33075748
2023-05-23 18:10:18,456 - INFO - buying power is: 308353.4
2023-05-23 18:10:18,457 - INFO - last trade price is: 27227.33075748
2023-05-23 18:10:18,457 - INFO - holding amount is: 2.81580195
2023-05-23 18:10:19,918 - ERROR - Buy Order submission failed
Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 234, in _one_request
    resp.raise_for_status()
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://paper-api.alpaca.markets/v2/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/main.py", line 73, in grid_trading
    self.api.submit_order(ticker, buying_amount, 'buy', 'limit', time_in_force='gtc',limit_price=ask_price)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 429, in submit_order
    resp = self.post('/orders', params)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 253, in post
    return self._request('POST', path, data)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 242, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: insufficient balance for USD (requested: 30835.339981686957, available: 23454.63)
2023-05-23 18:10:19,919 - INFO - last trade price is: 27227.33075748
2023-05-23 18:10:21,200 - ERROR - Buy Order submission failed
Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 234, in _one_request
    resp.raise_for_status()
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://paper-api.alpaca.markets/v2/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/main.py", line 73, in grid_trading
    self.api.submit_order(ticker, buying_amount, 'buy', 'limit', time_in_force='gtc',limit_price=ask_price)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 429, in submit_order
    resp = self.post('/orders', params)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 253, in post
    return self._request('POST', path, data)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 242, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: insufficient balance for USD (requested: 30835.339981686957, available: 23454.63)
2023-05-23 18:10:21,201 - INFO - last trade price is: 27227.33075748
2023-05-23 18:10:22,489 - ERROR - Buy Order submission failed
Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 234, in _one_request
    resp.raise_for_status()
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://paper-api.alpaca.markets/v2/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/main.py", line 73, in grid_trading
    self.api.submit_order(ticker, buying_amount, 'buy', 'limit', time_in_force='gtc',limit_price=ask_price)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 429, in submit_order
    resp = self.post('/orders', params)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 253, in post
    return self._request('POST', path, data)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 242, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: insufficient balance for USD (requested: 30835.339981686957, available: 23454.63)
2023-05-23 18:10:22,490 - INFO - last trade price is: 27227.33075748
2023-05-23 18:10:23,781 - ERROR - Buy Order submission failed
Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 234, in _one_request
    resp.raise_for_status()
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://paper-api.alpaca.markets/v2/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/main.py", line 73, in grid_trading
    self.api.submit_order(ticker, buying_amount, 'buy', 'limit', time_in_force='gtc',limit_price=ask_price)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 429, in submit_order
    resp = self.post('/orders', params)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 253, in post
    return self._request('POST', path, data)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 242, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: insufficient balance for USD (requested: 30835.339981686957, available: 23454.63)
2023-05-23 18:10:23,783 - INFO - last trade price is: 27227.33075748
2023-05-23 18:10:25,064 - ERROR - Buy Order submission failed
Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 234, in _one_request
    resp.raise_for_status()
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://paper-api.alpaca.markets/v2/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/main.py", line 73, in grid_trading
    self.api.submit_order(ticker, buying_amount, 'buy', 'limit', time_in_force='gtc',limit_price=ask_price)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 429, in submit_order
    resp = self.post('/orders', params)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 253, in post
    return self._request('POST', path, data)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 242, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: insufficient balance for USD (requested: 30835.339994682320025, available: 23454.63)
2023-05-23 18:10:25,065 - INFO - last trade price is: 27227.33075748
2023-05-23 18:10:26,354 - ERROR - Buy Order submission failed
Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 234, in _one_request
    resp.raise_for_status()
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://paper-api.alpaca.markets/v2/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/main.py", line 73, in grid_trading
    self.api.submit_order(ticker, buying_amount, 'buy', 'limit', time_in_force='gtc',limit_price=ask_price)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 429, in submit_order
    resp = self.post('/orders', params)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 253, in post
    return self._request('POST', path, data)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 242, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: insufficient balance for USD (requested: 30835.339994682320025, available: 23454.63)
2023-05-23 18:10:26,363 - INFO - last trade price is: 27227.33075748
2023-05-23 18:10:27,668 - ERROR - Buy Order submission failed
Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 234, in _one_request
    resp.raise_for_status()
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://paper-api.alpaca.markets/v2/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/main.py", line 73, in grid_trading
    self.api.submit_order(ticker, buying_amount, 'buy', 'limit', time_in_force='gtc',limit_price=ask_price)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 429, in submit_order
    resp = self.post('/orders', params)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 253, in post
    return self._request('POST', path, data)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 242, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: insufficient balance for USD (requested: 30835.339994682320025, available: 23454.63)
2023-05-23 18:10:27,669 - INFO - last trade price is: 27227.33075748
2023-05-23 18:10:28,976 - ERROR - Buy Order submission failed
Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 234, in _one_request
    resp.raise_for_status()
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://paper-api.alpaca.markets/v2/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/main.py", line 73, in grid_trading
    self.api.submit_order(ticker, buying_amount, 'buy', 'limit', time_in_force='gtc',limit_price=ask_price)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 429, in submit_order
    resp = self.post('/orders', params)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 253, in post
    return self._request('POST', path, data)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 242, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: insufficient balance for USD (requested: 30835.339994682320025, available: 23454.63)
2023-05-23 18:10:28,978 - INFO - last trade price is: 27227.33075748
2023-05-23 18:11:16,742 - ERROR - Buy Order submission failed
Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 234, in _one_request
    resp.raise_for_status()
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://paper-api.alpaca.markets/v2/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/main.py", line 73, in grid_trading
    self.api.submit_order(ticker, buying_amount, 'buy', 'limit', time_in_force='gtc',limit_price=ask_price)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 429, in submit_order
    resp = self.post('/orders', params)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 253, in post
    return self._request('POST', path, data)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 242, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: insufficient balance for USD (requested: 30835.3399946434224, available: 23454.63)
2023-05-23 18:11:16,742 - INFO - last trade price is: 27227.33075748
2023-05-23 18:11:18,023 - ERROR - Buy Order submission failed
Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 234, in _one_request
    resp.raise_for_status()
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://paper-api.alpaca.markets/v2/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/main.py", line 73, in grid_trading
    self.api.submit_order(ticker, buying_amount, 'buy', 'limit', time_in_force='gtc',limit_price=ask_price)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 429, in submit_order
    resp = self.post('/orders', params)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 253, in post
    return self._request('POST', path, data)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 242, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: insufficient balance for USD (requested: 30835.3399946434224, available: 23454.63)
2023-05-23 18:11:18,023 - INFO - last trade price is: 27227.33075748
2023-05-23 18:11:19,316 - ERROR - Buy Order submission failed
Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 234, in _one_request
    resp.raise_for_status()
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://paper-api.alpaca.markets/v2/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/main.py", line 73, in grid_trading
    self.api.submit_order(ticker, buying_amount, 'buy', 'limit', time_in_force='gtc',limit_price=ask_price)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 429, in submit_order
    resp = self.post('/orders', params)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 253, in post
    return self._request('POST', path, data)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 242, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: insufficient balance for USD (requested: 30835.3399946434224, available: 23454.63)
2023-05-23 18:11:19,318 - INFO - last trade price is: 27227.33075748
2023-05-23 18:11:20,589 - ERROR - Buy Order submission failed
Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 234, in _one_request
    resp.raise_for_status()
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://paper-api.alpaca.markets/v2/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/main.py", line 73, in grid_trading
    self.api.submit_order(ticker, buying_amount, 'buy', 'limit', time_in_force='gtc',limit_price=ask_price)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 429, in submit_order
    resp = self.post('/orders', params)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 253, in post
    return self._request('POST', path, data)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 242, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: insufficient balance for USD (requested: 30835.3399755480695, available: 23454.63)
2023-05-23 18:11:20,590 - INFO - last trade price is: 27227.33075748
2023-05-23 18:11:21,867 - ERROR - Buy Order submission failed
Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 234, in _one_request
    resp.raise_for_status()
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://paper-api.alpaca.markets/v2/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/main.py", line 73, in grid_trading
    self.api.submit_order(ticker, buying_amount, 'buy', 'limit', time_in_force='gtc',limit_price=ask_price)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 429, in submit_order
    resp = self.post('/orders', params)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 253, in post
    return self._request('POST', path, data)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 242, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: insufficient balance for USD (requested: 30835.3399755480695, available: 23454.63)
2023-05-23 18:11:21,867 - INFO - last trade price is: 27227.33075748
2023-05-23 18:11:23,151 - ERROR - Buy Order submission failed
Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 234, in _one_request
    resp.raise_for_status()
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://paper-api.alpaca.markets/v2/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/main.py", line 73, in grid_trading
    self.api.submit_order(ticker, buying_amount, 'buy', 'limit', time_in_force='gtc',limit_price=ask_price)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 429, in submit_order
    resp = self.post('/orders', params)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 253, in post
    return self._request('POST', path, data)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 242, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: insufficient balance for USD (requested: 30835.3399755480695, available: 23454.63)
2023-05-23 18:11:23,152 - INFO - last trade price is: 27227.33075748
2023-05-23 18:11:24,432 - ERROR - Buy Order submission failed
Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 234, in _one_request
    resp.raise_for_status()
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://paper-api.alpaca.markets/v2/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/main.py", line 73, in grid_trading
    self.api.submit_order(ticker, buying_amount, 'buy', 'limit', time_in_force='gtc',limit_price=ask_price)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 429, in submit_order
    resp = self.post('/orders', params)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 253, in post
    return self._request('POST', path, data)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 242, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: insufficient balance for USD (requested: 30835.3399755480695, available: 23454.63)
2023-05-23 18:11:24,433 - INFO - last trade price is: 27227.33075748
2023-05-23 18:11:25,723 - ERROR - Buy Order submission failed
Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 234, in _one_request
    resp.raise_for_status()
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://paper-api.alpaca.markets/v2/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/main.py", line 73, in grid_trading
    self.api.submit_order(ticker, buying_amount, 'buy', 'limit', time_in_force='gtc',limit_price=ask_price)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 429, in submit_order
    resp = self.post('/orders', params)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 253, in post
    return self._request('POST', path, data)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 242, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: insufficient balance for USD (requested: 30835.33999949, available: 23454.63)
2023-05-23 18:11:25,724 - INFO - last trade price is: 27227.33075748
2023-05-23 18:11:27,004 - ERROR - Buy Order submission failed
Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 234, in _one_request
    resp.raise_for_status()
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://paper-api.alpaca.markets/v2/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/main.py", line 73, in grid_trading
    self.api.submit_order(ticker, buying_amount, 'buy', 'limit', time_in_force='gtc',limit_price=ask_price)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 429, in submit_order
    resp = self.post('/orders', params)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 253, in post
    return self._request('POST', path, data)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 242, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: insufficient balance for USD (requested: 30835.33999949, available: 23454.63)
2023-05-23 18:11:27,004 - INFO - last trade price is: 27227.33075748
2023-05-23 18:11:28,296 - ERROR - Buy Order submission failed
Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 234, in _one_request
    resp.raise_for_status()
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://paper-api.alpaca.markets/v2/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/main.py", line 73, in grid_trading
    self.api.submit_order(ticker, buying_amount, 'buy', 'limit', time_in_force='gtc',limit_price=ask_price)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 429, in submit_order
    resp = self.post('/orders', params)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 253, in post
    return self._request('POST', path, data)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 242, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: insufficient balance for USD (requested: 30835.33999949, available: 23454.63)
2023-05-23 18:11:28,298 - INFO - last trade price is: 27227.33075748
2023-05-23 18:11:29,575 - ERROR - Buy Order submission failed
Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 234, in _one_request
    resp.raise_for_status()
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://paper-api.alpaca.markets/v2/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/main.py", line 73, in grid_trading
    self.api.submit_order(ticker, buying_amount, 'buy', 'limit', time_in_force='gtc',limit_price=ask_price)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 429, in submit_order
    resp = self.post('/orders', params)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 253, in post
    return self._request('POST', path, data)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 242, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: insufficient balance for USD (requested: 30835.33999949, available: 23454.63)
2023-05-23 18:11:29,576 - INFO - last trade price is: 27227.33075748
2023-05-23 18:11:30,836 - ERROR - Buy Order submission failed
Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 234, in _one_request
    resp.raise_for_status()
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://paper-api.alpaca.markets/v2/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/main.py", line 73, in grid_trading
    self.api.submit_order(ticker, buying_amount, 'buy', 'limit', time_in_force='gtc',limit_price=ask_price)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 429, in submit_order
    resp = self.post('/orders', params)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 253, in post
    return self._request('POST', path, data)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 242, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: insufficient balance for USD (requested: 30835.33998215212578609, available: 23454.63)
2023-05-23 18:11:30,836 - INFO - last trade price is: 27227.33075748
2023-05-23 18:11:32,130 - ERROR - Buy Order submission failed
Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 234, in _one_request
    resp.raise_for_status()
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://paper-api.alpaca.markets/v2/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/main.py", line 73, in grid_trading
    self.api.submit_order(ticker, buying_amount, 'buy', 'limit', time_in_force='gtc',limit_price=ask_price)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 429, in submit_order
    resp = self.post('/orders', params)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 253, in post
    return self._request('POST', path, data)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 242, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: insufficient balance for USD (requested: 30835.33998215212578609, available: 23454.63)
2023-05-23 18:11:32,131 - INFO - last trade price is: 27227.33075748
2023-05-23 18:11:33,411 - ERROR - Buy Order submission failed
Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 234, in _one_request
    resp.raise_for_status()
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://paper-api.alpaca.markets/v2/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/main.py", line 73, in grid_trading
    self.api.submit_order(ticker, buying_amount, 'buy', 'limit', time_in_force='gtc',limit_price=ask_price)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 429, in submit_order
    resp = self.post('/orders', params)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 253, in post
    return self._request('POST', path, data)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 242, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: insufficient balance for USD (requested: 30835.33998215212578609, available: 23454.63)
2023-05-23 18:11:33,412 - INFO - last trade price is: 27227.33075748
2023-05-23 18:11:40,636 - ERROR - Buy Order submission failed
Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 234, in _one_request
    resp.raise_for_status()
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://paper-api.alpaca.markets/v2/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/main.py", line 73, in grid_trading
    self.api.submit_order(ticker, buying_amount, 'buy', 'limit', time_in_force='gtc',limit_price=ask_price)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 429, in submit_order
    resp = self.post('/orders', params)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 253, in post
    return self._request('POST', path, data)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 242, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: insufficient balance for USD (requested: 30835.339999280838, available: 23454.63)
2023-05-23 18:11:40,636 - INFO - last trade price is: 27227.33075748
2023-05-23 18:11:41,908 - ERROR - Buy Order submission failed
Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 234, in _one_request
    resp.raise_for_status()
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://paper-api.alpaca.markets/v2/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/main.py", line 73, in grid_trading
    self.api.submit_order(ticker, buying_amount, 'buy', 'limit', time_in_force='gtc',limit_price=ask_price)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 429, in submit_order
    resp = self.post('/orders', params)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 253, in post
    return self._request('POST', path, data)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 242, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: insufficient balance for USD (requested: 30835.339999280838, available: 23454.63)
2023-05-23 18:11:41,909 - INFO - last trade price is: 27227.33075748
2023-05-23 18:11:43,189 - ERROR - Buy Order submission failed
Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 234, in _one_request
    resp.raise_for_status()
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://paper-api.alpaca.markets/v2/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/main.py", line 73, in grid_trading
    self.api.submit_order(ticker, buying_amount, 'buy', 'limit', time_in_force='gtc',limit_price=ask_price)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 429, in submit_order
    resp = self.post('/orders', params)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 253, in post
    return self._request('POST', path, data)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 242, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: insufficient balance for USD (requested: 30835.339999280838, available: 23454.63)
2023-05-23 18:11:43,190 - INFO - last trade price is: 27227.33075748
2023-05-23 18:14:29,016 - INFO - buying power is: 23454.63234365907
2023-05-23 18:14:29,017 - INFO - last trade price is: 27227.33075748
2023-05-23 18:14:29,017 - INFO - holding amount is: 2.81580195
2023-05-23 18:15:32,537 - INFO - Bought 0.0862406782629898 of BTC/USD at price: 27196.716
2023-05-23 18:15:32,718 - INFO - last trade price is: 27196.716
2023-05-23 18:19:03,533 - INFO - buying power is: 21109.172434745436
2023-05-23 18:19:03,535 - INFO - last trade price is: 27196.716
2023-05-23 18:19:03,535 - INFO - holding amount is: 2.901852898
2023-05-23 18:25:03,511 - INFO - buying power is: 21109.172434745436
2023-05-23 18:25:03,512 - INFO - last trade price is: 27196.716
2023-05-23 18:25:03,512 - INFO - holding amount is: 2.901852898
2023-05-23 18:31:02,326 - INFO - buying power is: 21109.172434745436
2023-05-23 18:31:02,328 - INFO - last trade price is: 27196.716
2023-05-23 18:31:02,328 - INFO - holding amount is: 2.901852898
2023-05-23 18:55:33,057 - INFO - buying power is: 21109.172434745436
2023-05-23 18:55:33,058 - INFO - last trade price is: 27196.716
2023-05-23 18:55:33,058 - INFO - holding amount is: 2.901852898
2023-05-23 19:34:23,692 - INFO - buying power is: 21109.172434745436
2023-05-23 19:34:23,694 - INFO - last trade price is: 27196.716
2023-05-23 19:34:23,694 - INFO - holding amount is: 2.901852898
2023-05-23 19:40:25,440 - INFO - buying power is: 21109.172434745436
2023-05-23 19:40:25,443 - INFO - last trade price is: 27196.716
2023-05-23 19:40:25,443 - INFO - holding amount is: 2.901852898
2023-05-23 19:50:23,545 - INFO - buying power is: 21109.172434745436
2023-05-23 19:50:23,547 - INFO - last trade price is: 27196.716
2023-05-23 19:50:23,548 - INFO - holding amount is: 2.901852898
2023-05-23 19:56:24,005 - INFO - buying power is: 21109.172434745436
2023-05-23 19:56:24,008 - INFO - last trade price is: 27196.716
2023-05-23 19:56:24,008 - INFO - holding amount is: 2.901852898
2023-05-23 20:51:10,983 - INFO - buying power is: 21109.172434745436
2023-05-23 20:51:10,985 - INFO - last trade price is: 27196.716
2023-05-23 20:51:10,985 - INFO - holding amount is: 2.901852898
2023-05-23 20:52:34,004 - INFO - buying power is: 21109.172434745436
2023-05-23 20:52:34,004 - INFO - last trade price is: 27196.716
2023-05-23 20:52:34,004 - INFO - holding amount is: 2.901852898
2023-05-23 20:57:13,943 - INFO - buying power is: 21109.172434745436
2023-05-23 20:57:13,946 - INFO - last trade price is: 27196.716
2023-05-23 20:57:13,946 - INFO - holding amount is: 2.901852898
2023-05-23 21:03:13,684 - INFO - buying power is: 21109.172434745436
2023-05-23 21:03:13,687 - INFO - last trade price is: 27196.716
2023-05-23 21:03:13,687 - INFO - holding amount is: 2.901852898
2023-05-23 21:11:21,240 - INFO - buying power is: 21109.172434745436
2023-05-23 21:11:21,242 - INFO - last trade price is: 27196.716
2023-05-23 21:11:21,242 - INFO - holding amount is: 2.901852898
2023-05-23 21:11:21,728 - INFO - Bought 0.07867737966378521 of BTC/USD at price: 26830.04
2023-05-23 21:11:21,919 - INFO - last trade price is: 26830.04
2023-05-23 21:13:19,327 - INFO - Bought 0.07089493791493075 of BTC/USD at price: 26797.8183
2023-05-23 21:13:19,528 - INFO - last trade price is: 26797.8183
2023-05-23 21:14:46,954 - INFO - buying power is: 17098.467006225
2023-05-23 21:14:46,955 - INFO - last trade price is: 26797.8183
2023-05-23 21:14:46,955 - INFO - holding amount is: 3.051167049
2023-05-23 21:20:47,169 - INFO - buying power is: 17098.467006225
2023-05-23 21:20:47,171 - INFO - last trade price is: 26797.8183
2023-05-23 21:20:47,171 - INFO - holding amount is: 3.051167049
2023-05-23 21:26:47,593 - INFO - buying power is: 17098.467006225
2023-05-23 21:26:47,595 - INFO - last trade price is: 26797.8183
2023-05-23 21:26:47,595 - INFO - holding amount is: 3.051167049
2023-05-23 21:32:48,073 - INFO - buying power is: 17098.467006225
2023-05-23 21:32:48,073 - INFO - last trade price is: 26797.8183
2023-05-23 21:32:48,074 - INFO - holding amount is: 3.051167049
2023-05-23 21:38:47,376 - INFO - buying power is: 17098.467006225
2023-05-23 21:38:47,378 - INFO - last trade price is: 26797.8183
2023-05-23 21:38:47,378 - INFO - holding amount is: 3.051167049
2023-05-23 21:44:47,443 - INFO - buying power is: 17098.467006225
2023-05-23 21:44:47,445 - INFO - last trade price is: 26797.8183
2023-05-23 21:44:47,445 - INFO - holding amount is: 3.051167049
2023-05-23 21:50:47,988 - INFO - buying power is: 17098.467006225
2023-05-23 21:50:47,991 - INFO - last trade price is: 26797.8183
2023-05-23 21:50:47,992 - INFO - holding amount is: 3.051167049
2023-05-23 22:06:15,099 - INFO - Sold out of -1s
2023-05-23 22:06:15,100 - INFO - last trade price is: 26840.4803832
2023-05-23 22:08:58,171 - INFO - buying power is: 18806.253693249342
2023-05-23 22:08:58,174 - INFO - last trade price is: 26840.4803832
2023-05-23 22:08:58,174 - INFO - holding amount is: 2.987463022
2023-05-23 22:08:58,654 - INFO - Sold out of -1s
2023-05-23 22:08:58,654 - INFO - last trade price is: 26848.97
2023-05-23 22:15:00,577 - INFO - buying power is: 20683.060625410104
2023-05-23 22:15:00,580 - INFO - last trade price is: 26848.97
2023-05-23 22:15:00,580 - INFO - holding amount is: 2.917418422
2023-05-23 22:21:01,433 - INFO - buying power is: 20683.060625410104
2023-05-23 22:21:01,434 - INFO - last trade price is: 26848.97
2023-05-23 22:21:01,434 - INFO - holding amount is: 2.917418422
2023-05-23 22:22:47,357 - INFO - Sold out of -1s
2023-05-23 22:22:47,358 - INFO - last trade price is: 26854.778
2023-05-23 22:27:02,787 - INFO - buying power is: 22748.876670709808
2023-05-23 22:27:02,790 - INFO - last trade price is: 26854.778
2023-05-23 22:27:02,790 - INFO - holding amount is: 2.840400245
2023-05-23 22:33:03,970 - INFO - buying power is: 22748.876670709808
2023-05-23 22:33:03,972 - INFO - last trade price is: 26854.778
2023-05-23 22:33:03,972 - INFO - holding amount is: 2.840400245
2023-05-23 22:38:03,168 - INFO - Bought 0.08482375599336282 of BTC/USD at price: 26818.992397
2023-05-23 22:38:03,357 - INFO - last trade price is: 26818.992397
2023-05-23 22:39:05,780 - INFO - buying power is: 20474.361609886808
2023-05-23 22:39:05,783 - INFO - last trade price is: 26818.992397
2023-05-23 22:39:05,783 - INFO - holding amount is: 2.925037387
2023-05-23 22:45:07,368 - INFO - buying power is: 20474.361609886808
2023-05-23 22:45:07,370 - INFO - last trade price is: 26818.992397
2023-05-23 22:45:07,371 - INFO - holding amount is: 2.925037387
2023-05-23 22:51:09,567 - INFO - buying power is: 20474.361609886808
2023-05-23 22:51:09,570 - INFO - last trade price is: 26818.992397
2023-05-23 22:51:09,570 - INFO - holding amount is: 2.925037387
2023-05-23 22:57:11,785 - INFO - buying power is: 20474.361609886808
2023-05-23 22:57:11,788 - INFO - last trade price is: 26818.992397
2023-05-23 22:57:11,788 - INFO - holding amount is: 2.925037387
2023-05-23 23:03:13,155 - INFO - buying power is: 20474.361609886808
2023-05-23 23:03:13,158 - INFO - last trade price is: 26818.992397
2023-05-23 23:03:13,158 - INFO - holding amount is: 2.925037387
2023-05-23 23:09:14,146 - INFO - buying power is: 20474.361609886808
2023-05-23 23:09:14,147 - INFO - last trade price is: 26818.992397
2023-05-23 23:09:14,148 - INFO - holding amount is: 2.925037387
2023-05-23 23:15:14,238 - INFO - buying power is: 20474.361609886808
2023-05-23 23:15:14,241 - INFO - last trade price is: 26818.992397
2023-05-23 23:15:14,242 - INFO - holding amount is: 2.925037387
2023-05-23 23:21:15,831 - INFO - buying power is: 20474.361609886808
2023-05-23 23:21:15,834 - INFO - last trade price is: 26818.992397
2023-05-23 23:21:15,834 - INFO - holding amount is: 2.925037387
2023-05-23 23:30:18,878 - ERROR - Buy Order submission failed
Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1322, in getresponse
    response.begin()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 357, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='paper-api.alpaca.markets', port=443): Read timed out. (read timeout=None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/main.py", line 73, in grid_trading
    self.api.submit_order(ticker, buying_amount, 'buy', 'limit', time_in_force='gtc',limit_price=ask_price)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 429, in submit_order
    resp = self.post('/orders', params)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 253, in post
    return self._request('POST', path, data)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 232, in _one_request
    resp = self._session.request(method, url, **opts)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/Users/xinyaoli/PycharmProjects/Alpaca-Test/venv/lib/python3.8/site-packages/requests/adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='paper-api.alpaca.markets', port=443): Read timed out. (read timeout=None)
2023-05-23 23:30:18,882 - INFO - last trade price is: 26818.992397
2023-05-23 23:31:27,148 - INFO - Bought 0.07641920633231791 of BTC/USD at price: 26792.1673
2023-05-23 23:31:27,348 - INFO - last trade price is: 26792.1673
2023-05-23 23:35:08,763 - INFO - buying power is: 18426.96176119633
2023-05-23 23:35:08,765 - INFO - last trade price is: 26792.1673
2023-05-23 23:35:08,765 - INFO - holding amount is: 3.00128847
